set identity_insert productcourses on
 INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence,Version) VALUES(1,'71836',1,'Easy','Chapter 1','End of chapter','One major advantage of push/pull steering from the low-hand position is________.',1, '0');
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence,Version) VALUES(2,'71836',2,'Medium','Chapter 1','End of chapter','If you are stuck in a traffic jam and you can feel your anger rising, you are experiencing a challenge called ________',2, '0');
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence,Version) VALUES(3,'71836',3,'Hard','Chapter 2','End of chapter','By law, if you are involved in a collision, _________',3, '0');
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence,Version) VALUES(4,'71836',4,'Easy','Chapter 1','End of chapter','While you are passing on a two-lane road, _________.',4, '0');
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence,Version) VALUES(5,'71836',5,'Medium','Chapter 3','End of chapter','If you can see an emergency vehicle with flashing lights ahead, ______.',5, '0');
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence,Version) VALUES(6,'71836',6,'Easy','Chapter 5','End of chapter','If you are involved in a collision and the vehicles are still operational, _______.',6, '0');
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence,Version) VALUES(7,'71836',7,'Hard','Chapter 6','End of chapter','Alcohol begins to affect you__________after it enters your body',7, '0');
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence,Version) VALUES(8,'71836',8,'Medium','Chapter 28','End of chapter','Text can be used with a diamond symbol to delineate__________.',8, '0');
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence,Version) VALUES(9,'71836',9,'Easy','Chapter 12','End of chapter',' When approaching a railroad crossing, you must look_____.',9, '0');
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence,Version) VALUES(10,'71836',10,'Medium','Chapter 7','End of chapter','New pedestrian and school zone signs exist on the roadway to warn drivers of an approaching crosswalk. They are_______',10, '0');
