set identity_insert productcourses on
 INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence) VALUES(1,'1',1,3,'Chapter 1','End of chapter','One major advantage of push/pull steering from the low-hand position is________.',1);
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence) VALUES(2,'1',2,2,'Chapter 1','End of chapter','If you are stuck in a traffic jam and you can feel your anger rising, you are experiencing a challenge called ________',2);
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence) VALUES(3,'1',3,1,'Chapter 2','End of chapter','By law, if you are involved in a collision, _________',3);
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence) VALUES(4,'1',4,3,'Chapter 1','End of chapter','While you are passing on a two-lane road, _________.',4);
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence) VALUES(5,'1',5,2,'Chapter 3','End of chapter','If you can see an emergency vehicle with flashing lights ahead, ______.',5);
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence) VALUES(6,'1',6,1,'Chapter 5','End of chapter','If you are involved in a collision and the vehicles are still operational, _______.',6);
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence) VALUES(7,'1',7,2,'Chapter 6','End of chapter','Alcohol begins to affect you__________after it enters your body',7);
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence) VALUES(8,'1',8,1,'Chapter 28','End of chapter','Text can be used with a diamond symbol to delineate__________.',8);
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence) VALUES(9,'1',9,1,'Chapter 12','End of chapter',' When approaching a railroad crossing, you must look_____.',9);
INSERT INTO ProductCourses(Id,ProductCourseDlapId,QuestionId,Difficulty,Chapter,Bank,Title,Sequence) VALUES(10,'1',10,3,'Chapter 7','End of chapter','New pedestrian and school zone signs exist on the roadway to warn drivers of an approaching crosswalk. They are_______',10);
