
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.[EmailTemplate]','U') IS NULL
BEGIN

	CREATE TABLE [dbo].[EmailTemplate](
	[Id] [int] NOT NULL,
	[TemplateText] [nvarchar](4000) NOT NULL,
	[TemplateHtml] [nvarchar](4000) NOT NULL,
	 CONSTRAINT [PK_EmailTemplate] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

END

GO