SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.[QuestionLogEventTypes]','U') IS NULL
BEGIN

	CREATE TABLE [dbo].[QuestionLogEventTypes](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[EventType] [nvarchar](100) NOT NULL,
	 CONSTRAINT [PK_QuestionLogEventType] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
	) ON [PRIMARY]
END

GO


