SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.[QuestionLogs]','U') IS NULL
BEGIN
	CREATE TABLE [dbo].[QuestionLogs](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[QuestionId] [nvarchar](100) NOT NULL,
		[CourseId] [nvarchar](100) NOT NULL,
		[UserId] [nvarchar](100) NOT NULL,
		[EventType] [int] NOT NULL,
		[Created] [datetime] NOT NULL,
	 CONSTRAINT [PK_QuestionLogs] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
	) ON [PRIMARY]
END
GO


