
/****** Object:  Table [dbo].[PxWebRights]    Script Date: 09/14/2012 15:32:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF OBJECT_ID('dbo.[PxWebRights]','U') IS NULL
BEGIN

CREATE TABLE [dbo].[PxWebRights](
	[PxWebRightId] [int] IDENTITY(1,1) NOT NULL,
	[PxWebRightType] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PxWebRights_1] PRIMARY KEY CLUSTERED 
(
	[PxWebRightId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

SET ANSI_PADDING OFF
GO


