
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.[UserTypes]','U') IS NULL
BEGIN

	CREATE TABLE [dbo].[UserTypes](
		[Id] [bigint] IDENTITY(1,1) NOT NULL,
		[UserId] [nvarchar](50) NOT NULL,
		[CourseId] [nvarchar](50) NOT NULL,
		[Type] [int] NOT NULL,
	 CONSTRAINT [PK_UserTypes] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[UserTypes]  WITH CHECK ADD  CONSTRAINT [FK_UserTypes_Users] FOREIGN KEY([UserId])
	REFERENCES [dbo].[Users] ([UserId])

	ALTER TABLE [dbo].[UserTypes] CHECK CONSTRAINT [FK_UserTypes_Users]

END

GO


