//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macmillan.PXQBA.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseMetaFields = new HashSet<CourseMetaField>();
        }
    
        public int Id { get; set; }
        public string DlapId { get; set; }
    
        public virtual ICollection<CourseMetaField> CourseMetaFields { get; set; }
    }
}
