//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macmillan.PXQBA.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMetaField
    {
        public CourseMetaField()
        {
            this.CourseMetaFieldValues = new HashSet<CourseMetaFieldValue>();
        }
    
        public int Id { get; set; }
        public string XMLFieldName { get; set; }
        public bool Filterable { get; set; }
        public string FriendlyName { get; set; }
        public string Type { get; set; }
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<CourseMetaFieldValue> CourseMetaFieldValues { get; set; }
    }
}
