//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macmillan.PXQBA.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCourse
    {
        public int Id { get; set; }
        public string ProductCourseDlapId { get; set; }
        public string Difficulty { get; set; }
        public string Chapter { get; set; }
        public string Bank { get; set; }
        public string Title { get; set; }
        public string Sequence { get; set; }
        public int QuestionId { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
