//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macmillan.PXQBA.DataAccess.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QBADummyModelContainer : DbContext
    {
        public QBADummyModelContainer()
            : base("name=QBADummyModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<ProductCourse> ProductCourses { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseMetaField> CourseMetaFields { get; set; }
        public virtual DbSet<CourseMetaFieldValue> CourseMetaFieldValues { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
    }
}
