//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QBADummyModel", "QuestionProductCourse", "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Macmillan.PXQBA.DataAccess.Data.Question), "ProductCourse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Macmillan.PXQBA.DataAccess.Data.ProductCourse), true)]
[assembly: EdmRelationshipAttribute("QBADummyModel", "CourseCourseMetaField", "Course", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Macmillan.PXQBA.DataAccess.Data.Course), "CourseMetaField", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Macmillan.PXQBA.DataAccess.Data.CourseMetaField), true)]
[assembly: EdmRelationshipAttribute("QBADummyModel", "CourseMetaFieldCourseMetaFieldValue", "CourseMetaField", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Macmillan.PXQBA.DataAccess.Data.CourseMetaField), "CourseMetaFieldValue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Macmillan.PXQBA.DataAccess.Data.CourseMetaFieldValue), true)]
[assembly: EdmRelationshipAttribute("QBADummyModel", "QuestionNote", "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Macmillan.PXQBA.DataAccess.Data.Question), "Note", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Macmillan.PXQBA.DataAccess.Data.Note), true)]

#endregion

namespace Macmillan.PXQBA.DataAccess.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QBADummyModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QBADummyModelContainer object using the connection string found in the 'QBADummyModelContainer' section of the application configuration file.
        /// </summary>
        public QBADummyModelContainer() : base("name=QBADummyModelContainer", "QBADummyModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QBADummyModelContainer object.
        /// </summary>
        public QBADummyModelContainer(string connectionString) : base(connectionString, "QBADummyModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QBADummyModelContainer object.
        /// </summary>
        public QBADummyModelContainer(EntityConnection connection) : base(connection, "QBADummyModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Question> Questions
        {
            get
            {
                if ((_Questions == null))
                {
                    _Questions = base.CreateObjectSet<Question>("Questions");
                }
                return _Questions;
            }
        }
        private ObjectSet<Question> _Questions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductCourse> ProductCourses
        {
            get
            {
                if ((_ProductCourses == null))
                {
                    _ProductCourses = base.CreateObjectSet<ProductCourse>("ProductCourses");
                }
                return _ProductCourses;
            }
        }
        private ObjectSet<ProductCourse> _ProductCourses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Course> Courses
        {
            get
            {
                if ((_Courses == null))
                {
                    _Courses = base.CreateObjectSet<Course>("Courses");
                }
                return _Courses;
            }
        }
        private ObjectSet<Course> _Courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CourseMetaField> CourseMetaFields
        {
            get
            {
                if ((_CourseMetaFields == null))
                {
                    _CourseMetaFields = base.CreateObjectSet<CourseMetaField>("CourseMetaFields");
                }
                return _CourseMetaFields;
            }
        }
        private ObjectSet<CourseMetaField> _CourseMetaFields;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CourseMetaFieldValue> CourseMetaFieldValues
        {
            get
            {
                if ((_CourseMetaFieldValues == null))
                {
                    _CourseMetaFieldValues = base.CreateObjectSet<CourseMetaFieldValue>("CourseMetaFieldValues");
                }
                return _CourseMetaFieldValues;
            }
        }
        private ObjectSet<CourseMetaFieldValue> _CourseMetaFieldValues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Note> Notes
        {
            get
            {
                if ((_Notes == null))
                {
                    _Notes = base.CreateObjectSet<Note>("Notes");
                }
                return _Notes;
            }
        }
        private ObjectSet<Note> _Notes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Questions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuestions(Question question)
        {
            base.AddObject("Questions", question);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductCourses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductCourses(ProductCourse productCourse)
        {
            base.AddObject("ProductCourses", productCourse);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourses(Course course)
        {
            base.AddObject("Courses", course);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CourseMetaFields EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseMetaFields(CourseMetaField courseMetaField)
        {
            base.AddObject("CourseMetaFields", courseMetaField);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CourseMetaFieldValues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseMetaFieldValues(CourseMetaFieldValue courseMetaFieldValue)
        {
            base.AddObject("CourseMetaFieldValues", courseMetaFieldValue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Notes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNotes(Note note)
        {
            base.AddObject("Notes", note);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBADummyModel", Name="Course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Course : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Course object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dlapId">Initial value of the DlapId property.</param>
        public static Course CreateCourse(global::System.Int32 id, global::System.String dlapId)
        {
            Course course = new Course();
            course.Id = id;
            course.DlapId = dlapId;
            return course;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DlapId
        {
            get
            {
                return _DlapId;
            }
            set
            {
                OnDlapIdChanging(value);
                ReportPropertyChanging("DlapId");
                _DlapId = StructuralObject.SetValidValue(value, false, "DlapId");
                ReportPropertyChanged("DlapId");
                OnDlapIdChanged();
            }
        }
        private global::System.String _DlapId;
        partial void OnDlapIdChanging(global::System.String value);
        partial void OnDlapIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBADummyModel", "CourseCourseMetaField", "CourseMetaField")]
        public EntityCollection<CourseMetaField> CourseMetaFields
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CourseMetaField>("QBADummyModel.CourseCourseMetaField", "CourseMetaField");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CourseMetaField>("QBADummyModel.CourseCourseMetaField", "CourseMetaField", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBADummyModel", Name="CourseMetaField")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseMetaField : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CourseMetaField object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="xMLFieldName">Initial value of the XMLFieldName property.</param>
        /// <param name="filterable">Initial value of the Filterable property.</param>
        /// <param name="friendlyName">Initial value of the FriendlyName property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="courseId">Initial value of the CourseId property.</param>
        public static CourseMetaField CreateCourseMetaField(global::System.Int32 id, global::System.String xMLFieldName, global::System.Boolean filterable, global::System.String friendlyName, global::System.String type, global::System.Int32 courseId)
        {
            CourseMetaField courseMetaField = new CourseMetaField();
            courseMetaField.Id = id;
            courseMetaField.XMLFieldName = xMLFieldName;
            courseMetaField.Filterable = filterable;
            courseMetaField.FriendlyName = friendlyName;
            courseMetaField.Type = type;
            courseMetaField.CourseId = courseId;
            return courseMetaField;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String XMLFieldName
        {
            get
            {
                return _XMLFieldName;
            }
            set
            {
                OnXMLFieldNameChanging(value);
                ReportPropertyChanging("XMLFieldName");
                _XMLFieldName = StructuralObject.SetValidValue(value, false, "XMLFieldName");
                ReportPropertyChanged("XMLFieldName");
                OnXMLFieldNameChanged();
            }
        }
        private global::System.String _XMLFieldName;
        partial void OnXMLFieldNameChanging(global::System.String value);
        partial void OnXMLFieldNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Filterable
        {
            get
            {
                return _Filterable;
            }
            set
            {
                OnFilterableChanging(value);
                ReportPropertyChanging("Filterable");
                _Filterable = StructuralObject.SetValidValue(value, "Filterable");
                ReportPropertyChanged("Filterable");
                OnFilterableChanged();
            }
        }
        private global::System.Boolean _Filterable;
        partial void OnFilterableChanging(global::System.Boolean value);
        partial void OnFilterableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FriendlyName
        {
            get
            {
                return _FriendlyName;
            }
            set
            {
                OnFriendlyNameChanging(value);
                ReportPropertyChanging("FriendlyName");
                _FriendlyName = StructuralObject.SetValidValue(value, false, "FriendlyName");
                ReportPropertyChanged("FriendlyName");
                OnFriendlyNameChanged();
            }
        }
        private global::System.String _FriendlyName;
        partial void OnFriendlyNameChanging(global::System.String value);
        partial void OnFriendlyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                OnCourseIdChanging(value);
                ReportPropertyChanging("CourseId");
                _CourseId = StructuralObject.SetValidValue(value, "CourseId");
                ReportPropertyChanged("CourseId");
                OnCourseIdChanged();
            }
        }
        private global::System.Int32 _CourseId;
        partial void OnCourseIdChanging(global::System.Int32 value);
        partial void OnCourseIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBADummyModel", "CourseCourseMetaField", "Course")]
        public Course Course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("QBADummyModel.CourseCourseMetaField", "Course").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("QBADummyModel.CourseCourseMetaField", "Course").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Course> CourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("QBADummyModel.CourseCourseMetaField", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Course>("QBADummyModel.CourseCourseMetaField", "Course", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBADummyModel", "CourseMetaFieldCourseMetaFieldValue", "CourseMetaFieldValue")]
        public EntityCollection<CourseMetaFieldValue> CourseMetaFieldValues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CourseMetaFieldValue>("QBADummyModel.CourseMetaFieldCourseMetaFieldValue", "CourseMetaFieldValue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CourseMetaFieldValue>("QBADummyModel.CourseMetaFieldCourseMetaFieldValue", "CourseMetaFieldValue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBADummyModel", Name="CourseMetaFieldValue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseMetaFieldValue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CourseMetaFieldValue object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sequence">Initial value of the Sequence property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="courseMetaFieldId">Initial value of the CourseMetaFieldId property.</param>
        public static CourseMetaFieldValue CreateCourseMetaFieldValue(global::System.Int32 id, global::System.String sequence, global::System.String text, global::System.Int32 courseMetaFieldId)
        {
            CourseMetaFieldValue courseMetaFieldValue = new CourseMetaFieldValue();
            courseMetaFieldValue.Id = id;
            courseMetaFieldValue.Sequence = sequence;
            courseMetaFieldValue.Text = text;
            courseMetaFieldValue.CourseMetaFieldId = courseMetaFieldId;
            return courseMetaFieldValue;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                OnSequenceChanging(value);
                ReportPropertyChanging("Sequence");
                _Sequence = StructuralObject.SetValidValue(value, false, "Sequence");
                ReportPropertyChanged("Sequence");
                OnSequenceChanged();
            }
        }
        private global::System.String _Sequence;
        partial void OnSequenceChanging(global::System.String value);
        partial void OnSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false, "Text");
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CourseMetaFieldId
        {
            get
            {
                return _CourseMetaFieldId;
            }
            set
            {
                OnCourseMetaFieldIdChanging(value);
                ReportPropertyChanging("CourseMetaFieldId");
                _CourseMetaFieldId = StructuralObject.SetValidValue(value, "CourseMetaFieldId");
                ReportPropertyChanged("CourseMetaFieldId");
                OnCourseMetaFieldIdChanged();
            }
        }
        private global::System.Int32 _CourseMetaFieldId;
        partial void OnCourseMetaFieldIdChanging(global::System.Int32 value);
        partial void OnCourseMetaFieldIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBADummyModel", "CourseMetaFieldCourseMetaFieldValue", "CourseMetaField")]
        public CourseMetaField CourseMetaField
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CourseMetaField>("QBADummyModel.CourseMetaFieldCourseMetaFieldValue", "CourseMetaField").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CourseMetaField>("QBADummyModel.CourseMetaFieldCourseMetaFieldValue", "CourseMetaField").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CourseMetaField> CourseMetaFieldReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CourseMetaField>("QBADummyModel.CourseMetaFieldCourseMetaFieldValue", "CourseMetaField");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CourseMetaField>("QBADummyModel.CourseMetaFieldCourseMetaFieldValue", "CourseMetaField", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBADummyModel", Name="Note")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Note : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Note object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="isFlagged">Initial value of the IsFlagged property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        public static Note CreateNote(global::System.Int32 id, global::System.String text, global::System.Boolean isFlagged, global::System.Int32 questionId)
        {
            Note note = new Note();
            note.Id = id;
            note.Text = text;
            note.IsFlagged = isFlagged;
            note.QuestionId = questionId;
            return note;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false, "Text");
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFlagged
        {
            get
            {
                return _IsFlagged;
            }
            set
            {
                OnIsFlaggedChanging(value);
                ReportPropertyChanging("IsFlagged");
                _IsFlagged = StructuralObject.SetValidValue(value, "IsFlagged");
                ReportPropertyChanged("IsFlagged");
                OnIsFlaggedChanged();
            }
        }
        private global::System.Boolean _IsFlagged;
        partial void OnIsFlaggedChanging(global::System.Boolean value);
        partial void OnIsFlaggedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Int32 _QuestionId;
        partial void OnQuestionIdChanging(global::System.Int32 value);
        partial void OnQuestionIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBADummyModel", "QuestionNote", "Question")]
        public Question Question
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("QBADummyModel.QuestionNote", "Question").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("QBADummyModel.QuestionNote", "Question").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Question> QuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("QBADummyModel.QuestionNote", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Question>("QBADummyModel.QuestionNote", "Question", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBADummyModel", Name="ProductCourse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductCourse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductCourse object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="productCourseDlapId">Initial value of the ProductCourseDlapId property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        public static ProductCourse CreateProductCourse(global::System.Int32 id, global::System.String productCourseDlapId, global::System.Int32 questionId)
        {
            ProductCourse productCourse = new ProductCourse();
            productCourse.Id = id;
            productCourse.ProductCourseDlapId = productCourseDlapId;
            productCourse.QuestionId = questionId;
            return productCourse;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductCourseDlapId
        {
            get
            {
                return _ProductCourseDlapId;
            }
            set
            {
                OnProductCourseDlapIdChanging(value);
                ReportPropertyChanging("ProductCourseDlapId");
                _ProductCourseDlapId = StructuralObject.SetValidValue(value, false, "ProductCourseDlapId");
                ReportPropertyChanged("ProductCourseDlapId");
                OnProductCourseDlapIdChanged();
            }
        }
        private global::System.String _ProductCourseDlapId;
        partial void OnProductCourseDlapIdChanging(global::System.String value);
        partial void OnProductCourseDlapIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Difficulty
        {
            get
            {
                return _Difficulty;
            }
            set
            {
                OnDifficultyChanging(value);
                ReportPropertyChanging("Difficulty");
                _Difficulty = StructuralObject.SetValidValue(value, true, "Difficulty");
                ReportPropertyChanged("Difficulty");
                OnDifficultyChanged();
            }
        }
        private global::System.String _Difficulty;
        partial void OnDifficultyChanging(global::System.String value);
        partial void OnDifficultyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Chapter
        {
            get
            {
                return _Chapter;
            }
            set
            {
                OnChapterChanging(value);
                ReportPropertyChanging("Chapter");
                _Chapter = StructuralObject.SetValidValue(value, true, "Chapter");
                ReportPropertyChanged("Chapter");
                OnChapterChanged();
            }
        }
        private global::System.String _Chapter;
        partial void OnChapterChanging(global::System.String value);
        partial void OnChapterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bank
        {
            get
            {
                return _Bank;
            }
            set
            {
                OnBankChanging(value);
                ReportPropertyChanging("Bank");
                _Bank = StructuralObject.SetValidValue(value, true, "Bank");
                ReportPropertyChanged("Bank");
                OnBankChanged();
            }
        }
        private global::System.String _Bank;
        partial void OnBankChanging(global::System.String value);
        partial void OnBankChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                OnSequenceChanging(value);
                ReportPropertyChanging("Sequence");
                _Sequence = StructuralObject.SetValidValue(value, "Sequence");
                ReportPropertyChanged("Sequence");
                OnSequenceChanged();
            }
        }
        private Nullable<global::System.Int32> _Sequence;
        partial void OnSequenceChanging(Nullable<global::System.Int32> value);
        partial void OnSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Int32 _QuestionId;
        partial void OnQuestionIdChanging(global::System.Int32 value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExcerciseNo
        {
            get
            {
                return _ExcerciseNo;
            }
            set
            {
                OnExcerciseNoChanging(value);
                ReportPropertyChanging("ExcerciseNo");
                _ExcerciseNo = StructuralObject.SetValidValue(value, true, "ExcerciseNo");
                ReportPropertyChanged("ExcerciseNo");
                OnExcerciseNoChanged();
            }
        }
        private global::System.String _ExcerciseNo;
        partial void OnExcerciseNoChanging(global::System.String value);
        partial void OnExcerciseNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Guidance
        {
            get
            {
                return _Guidance;
            }
            set
            {
                OnGuidanceChanging(value);
                ReportPropertyChanging("Guidance");
                _Guidance = StructuralObject.SetValidValue(value, true, "Guidance");
                ReportPropertyChanged("Guidance");
                OnGuidanceChanged();
            }
        }
        private global::System.String _Guidance;
        partial void OnGuidanceChanging(global::System.String value);
        partial void OnGuidanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, true, "Version");
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.String _Version = "\"0\"";
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CognitiveLevel
        {
            get
            {
                return _CognitiveLevel;
            }
            set
            {
                OnCognitiveLevelChanging(value);
                ReportPropertyChanging("CognitiveLevel");
                _CognitiveLevel = StructuralObject.SetValidValue(value, true, "CognitiveLevel");
                ReportPropertyChanged("CognitiveLevel");
                OnCognitiveLevelChanged();
            }
        }
        private global::System.String _CognitiveLevel;
        partial void OnCognitiveLevelChanging(global::System.String value);
        partial void OnCognitiveLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keywords
        {
            get
            {
                return _Keywords;
            }
            set
            {
                OnKeywordsChanging(value);
                ReportPropertyChanging("Keywords");
                _Keywords = StructuralObject.SetValidValue(value, true, "Keywords");
                ReportPropertyChanged("Keywords");
                OnKeywordsChanged();
            }
        }
        private global::System.String _Keywords;
        partial void OnKeywordsChanging(global::System.String value);
        partial void OnKeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SuggestedUse
        {
            get
            {
                return _SuggestedUse;
            }
            set
            {
                OnSuggestedUseChanging(value);
                ReportPropertyChanging("SuggestedUse");
                _SuggestedUse = StructuralObject.SetValidValue(value, true, "SuggestedUse");
                ReportPropertyChanged("SuggestedUse");
                OnSuggestedUseChanged();
            }
        }
        private global::System.String _SuggestedUse;
        partial void OnSuggestedUseChanging(global::System.String value);
        partial void OnSuggestedUseChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBADummyModel", "QuestionProductCourse", "Question")]
        public Question Question
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("QBADummyModel.QuestionProductCourse", "Question").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("QBADummyModel.QuestionProductCourse", "Question").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Question> QuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("QBADummyModel.QuestionProductCourse", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Question>("QBADummyModel.QuestionProductCourse", "Question", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBADummyModel", Name="Question")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Question : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Question object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static Question CreateQuestion(global::System.Int32 id, global::System.Int32 status)
        {
            Question question = new Question();
            question.Id = id;
            question.Status = status;
            return question;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InteractionType
        {
            get
            {
                return _InteractionType;
            }
            set
            {
                OnInteractionTypeChanging(value);
                ReportPropertyChanging("InteractionType");
                _InteractionType = StructuralObject.SetValidValue(value, true, "InteractionType");
                ReportPropertyChanged("InteractionType");
                OnInteractionTypeChanged();
            }
        }
        private global::System.String _InteractionType;
        partial void OnInteractionTypeChanging(global::System.String value);
        partial void OnInteractionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DlapId
        {
            get
            {
                return _DlapId;
            }
            set
            {
                OnDlapIdChanging(value);
                ReportPropertyChanging("DlapId");
                _DlapId = StructuralObject.SetValidValue(value, true, "DlapId");
                ReportPropertyChanged("DlapId");
                OnDlapIdChanged();
            }
        }
        private global::System.String _DlapId;
        partial void OnDlapIdChanging(global::System.String value);
        partial void OnDlapIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Preview
        {
            get
            {
                return _Preview;
            }
            set
            {
                OnPreviewChanging(value);
                ReportPropertyChanging("Preview");
                _Preview = StructuralObject.SetValidValue(value, true, "Preview");
                ReportPropertyChanged("Preview");
                OnPreviewChanged();
            }
        }
        private global::System.String _Preview;
        partial void OnPreviewChanging(global::System.String value);
        partial void OnPreviewChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBADummyModel", "QuestionProductCourse", "ProductCourse")]
        public EntityCollection<ProductCourse> ProductCourses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProductCourse>("QBADummyModel.QuestionProductCourse", "ProductCourse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProductCourse>("QBADummyModel.QuestionProductCourse", "ProductCourse", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBADummyModel", "QuestionNote", "Note")]
        public EntityCollection<Note> Notes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Note>("QBADummyModel.QuestionNote", "Note");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Note>("QBADummyModel.QuestionNote", "Note", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
