//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macmillan.PXQBA.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string InteractionType { get; set; }
        public string EBookChapter { get; set; }
        public string Sequency { get; set; }
        public string DlapId { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string QuestionBank { get; set; }
        public string Preview { get; set; }
    }
}
