SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.[rpt_ContentTypeMaster]','U') IS NULL
BEGIN
CREATE TABLE [dbo].[rpt_ContentTypeMaster](
	[ContentTypeID] [int] NOT NULL,
	[ContentTypeDesc] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Report_Category] PRIMARY KEY CLUSTERED 
(
	[ContentTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO


